[2023-11-29T14:26:41.426+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: football-etl.load_to_sql scheduled__2023-02-14T00:00:00+00:00 [queued]>
[2023-11-29T14:26:41.441+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: football-etl.load_to_sql scheduled__2023-02-14T00:00:00+00:00 [queued]>
[2023-11-29T14:26:41.442+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-29T14:26:41.443+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-11-29T14:26:41.443+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-29T14:26:41.645+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_to_sql> on 2023-02-14 00:00:00+00:00
[2023-11-29T14:26:41.655+0000] {standard_task_runner.py:55} INFO - Started process 202 to run task
[2023-11-29T14:26:41.658+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'football-etl', 'load_to_sql', 'scheduled__2023-02-14T00:00:00+00:00', '--job-id', '317', '--raw', '--subdir', 'DAGS_FOLDER/dag-football.py', '--cfg-path', '/tmp/tmpabax3he7']
[2023-11-29T14:26:41.658+0000] {standard_task_runner.py:83} INFO - Job 317: Subtask load_to_sql
[2023-11-29T14:26:41.727+0000] {task_command.py:388} INFO - Running <TaskInstance: football-etl.load_to_sql scheduled__2023-02-14T00:00:00+00:00 [running]> on host 6377c365460c
[2023-11-29T14:26:41.804+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=football-etl
AIRFLOW_CTX_TASK_ID=load_to_sql
AIRFLOW_CTX_EXECUTION_DATE=2023-02-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-14T00:00:00+00:00
[2023-11-29T14:26:41.807+0000] {load_to_sql.py:16} INFO - Reading the joined tables...
[2023-11-29T14:26:41.828+0000] {load_to_sql.py:23} INFO - Loading joined tables to PostgreSQL...
[2023-11-29T14:26:43.088+0000] {load_to_sql.py:46} ERROR - SQLAlchemyError occurred while connecting to the database: (psycopg2.OperationalError) connection to server at "lucky.db.elephantsql.com" (54.195.214.215), port 5432 failed: FATAL:  too many connections for role "xckamlge"

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-29T14:26:43.089+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-11-29T14:26:43.099+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=football-etl, task_id=load_to_sql, execution_date=20230214T000000, start_date=20231129T142641, end_date=20231129T142643
[2023-11-29T14:26:43.154+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-11-29T14:26:43.176+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
