[2023-11-29T13:03:22.208+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: football-etl.extract_market_value scheduled__2023-01-15T00:00:00+00:00 [queued]>
[2023-11-29T13:03:22.219+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: football-etl.extract_market_value scheduled__2023-01-15T00:00:00+00:00 [queued]>
[2023-11-29T13:03:22.219+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-29T13:03:22.220+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-11-29T13:03:22.220+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-29T13:03:22.235+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): extract_market_value> on 2023-01-15 00:00:00+00:00
[2023-11-29T13:03:22.244+0000] {standard_task_runner.py:55} INFO - Started process 828 to run task
[2023-11-29T13:03:22.247+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'football-etl', 'extract_market_value', 'scheduled__2023-01-15T00:00:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/dag-football.py', '--cfg-path', '/tmp/tmp1pgvo2kj']
[2023-11-29T13:03:22.248+0000] {standard_task_runner.py:83} INFO - Job 59: Subtask extract_market_value
[2023-11-29T13:03:22.319+0000] {task_command.py:388} INFO - Running <TaskInstance: football-etl.extract_market_value scheduled__2023-01-15T00:00:00+00:00 [running]> on host 6377c365460c
[2023-11-29T13:03:22.389+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=football-etl
AIRFLOW_CTX_TASK_ID=extract_market_value
AIRFLOW_CTX_EXECUTION_DATE=2023-01-15T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-15T00:00:00+00:00
[2023-11-29T13:03:26.398+0000] {extract_market_value.py:14} ERROR - Error Connecting: HTTPSConnectionPool(host='transfermarkt-api.vercel.app', port=443): Max retries exceeded with url: /competitions/GB1/clubs?season_id=2023 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f04705a4390>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2023-11-29T13:03:26.399+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/script/extract_market_value.py", line 63, in extract_mv
    teams_data = get_premier_league_teams(premier_league_teams_url)
  File "/opt/airflow/dags/script/extract_market_value.py", line 19, in get_premier_league_teams
    return response.json().get('clubs', []) if response.status_code == 200 else []
UnboundLocalError: local variable 'response' referenced before assignment
[2023-11-29T13:03:26.414+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=football-etl, task_id=extract_market_value, execution_date=20230115T000000, start_date=20231129T130322, end_date=20231129T130326
[2023-11-29T13:03:26.552+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 59 for task extract_market_value (local variable 'response' referenced before assignment; 828)
[2023-11-29T13:03:26.593+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-11-29T13:03:26.626+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
